#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Microsoft.WindowsAzure.Mobile.Android.Test.Resource", IsApplication=true)]

namespace Microsoft.WindowsAzure.Mobile.Android.Test
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int Description = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int List = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Log = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Login = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int RunStatus = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int RunTests = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ServiceKey = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int ServiceTags = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int ServiceUri = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int TestName = 2130837513;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Harness = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ListedGroup = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ListedTest = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Test = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MobileServiceKey = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int MobileServiceUri = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int RunTests = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Tags = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
